### ISSUE TITLE
Save feature is disabled

### ISSUE THREAD

**Issue by tiguchi** [kengruven/strukt-bugs#1]
Hi,

I just started playing a bit with Strukt and I really like the idea and presentation. However, I notice already a few issues, so I'll probably come back and create more tickets here.

This problem is a glaring one. There's no way to save a document. Which is vital, because Strukt crashes a lot while adding new operations and editing existing ones. So at the moment it seems to be impossible to finish through the creation of a workflow.

I made sure that I added the "Documents" folder to the list of approved folders, still the save option in the menu is disabled. Also the "open" option is disabled.

Here is a screen shot:
![screen shot 2017-03-29 at 7 33 38 pm](https://cloud.githubusercontent.com/assets/6569525/24485069/cb4f7d9a-14b6-11e7-9bc7-07c19cdc9ec0.png)

I also just enabled analytics and "share crash reports with developers" feature on my Mac, so I hope the crash logs will arrive on your end.

**Comment by kengruven** [comment]
Hi, tiguchi!

Thanks for taking a chance on a new (1.0) application!  So, there's really two halves to this issue.


The first half is that it's crashing a lot for you.  That's bad, and I apologize!  I'm not seeing any crash reports on my end yet, but I'm looking forward to them, because I want to fix them.  For me, that's job 1 of any program: don't crash.  It sounds like that's the root issue here.  It's fair to look for a workaround, but it's also fair to expect a program to not crash in the first place.


The other half -- not being able to Save -- is for me partially a design decision, and partially a matter of priority.  I'm focusing on interactive use first.  As soon as users can Save, then it starts to get pretty deep pretty quick:

 - When operation syntax/semantics change between releases, what happens when an old pipeline is loaded in a new version of the app, or vice versa?
 - Does the app need to be able to upgrade (or downgrade) other versions automatically?  Does the file format need to be human-editable, so users can fix it themselves?
 - Is there benefit to having the pipelines as files, or should it be a "shoebox" style app?  If it's a shoebox app, what's the user interface like?  (Bookmarks?)
 - For example, do people want to save them as files so they can share them, and if so, is there a sharing mechanism I could build that would be more convenient for everybody?

It's not yet obvious to me how saving should be implemented, so I've been specifically holding off on tackling that until I have a more concrete idea of the primary purpose.  It's all too easy to build something that works today but breaks when I release a new version next week, or is awkward to use, or doesn't really meet people's needs.

In your case, if the purpose is "So I can finish a workflow, because it keeps crashing", then first of all I need to fix the crashing.

I hope this doesn't come across as dismissive.  I absolutely agree that, somehow, users will need to be able to save their work.  It is definitely a solvable problem.  It's just not quite as simple as "flip a switch".


Thanks for taking the time to report this, and I look forward to any other feedback you have.

**Comment by karlsander** [comment]
I was really confused by this as well. I appreciate the issues with adding saving but the app really needs it. I would personally prefer file based over shoebox, unless you plan to port to iOS. Properly document based, with proxy icon, versioning, auto-save etc would be ideal IMHO. The app speaks to a relatively tech savvy audience so I think sharing files would be fine.

As far as upgrading through versions, the most common thing I see is: when you open an old file in a new version, it will ask you if you want to migrate the file, after that there's no way to go back. I would be happy with this.

**Comment by kengruven** [comment]
I think I've convinced myself that:
 - a document-based app is the way to go, for *saving* pipelines (iOS isn't out of the question, at some point, but files can work there, too: iWork does it)
 - files should be able to be used for *sharing* pipelines as well (though it might be nice to have a simple text format for pasting, too)
 - for extracting *custom operations*, a saved file can be problematic, but there are enough other issues around them that I think they're going to have to wait for Strukt 2, anyway

The good news is that Strukt's main class is already an NSDocument subclass, and has been moving towards using more NSDocument functionality over time.  (These changes don't make the release notes because they're not user-visible, yet.)

There are still lots of details to work out, especially around security, and versioning.

In the short term, I have simplified (in the next version, after 1.2.2) the File menu to only relevant commands.

**Comment by OKrause42** [comment]
Is this going to come to Strukt 1?
I often find myself from using Strukt to build more complex pipelines, because I know, I will need to scrap them right away again and can not reuse them later...

**Comment by kengruven** [comment]
I have some great big ideas for Strukt 2, but "saving" is not one of them.  I'm perfectly willing to add it to Strukt 1.

One of the things that held me back was that operations/flags (semantics) were changing quite a bit in the early versions.  That has mostly settled down now, which sidesteps many of the issues with upgrading.

The limiting factor now is simply the number of hours in a day.  (I've been spending 10-12 hours a day in the theatre, since Sunday, for an upcoming show.)  Thanks for keeping my feet to the fire on this.  I'll see what I can do, when I have a free minute.

**Comment by kengruven** [comment]
Strukt 1.5 is now live on the Mac App Store, and includes the ability to save and load pipelines.

Everyone, please give it a spin and let me know if this is useful, and what you had in mind, or if there's anything else I can do to improve it.

**Comment by karlsander** [comment]
Great to see that you went with document based. Seems like with the new stuff in iOS11, document based will work well if you eventually want to go there too.

I had stopped using the app in the meantime, because I really couldn't fit having to keep windows open into my workflow. Really looking forward to getting back into it now.

**Comment by OKrause42** [comment]
Brilliant - works great, many thanks!

**Comment by kengruven** [comment]
OK, I'm going to close this issue now.  If anyone has any issues related to saving/loading, feel free to comment or re-open.
