### ISSUE TITLE
Open is always greyed out, no way to open a file

### ISSUE THREAD

**Issue by AddictArts** [kengruven/strukt-bugs#12]
Yes I could drag and drop and yes I could type, but why have open and open recent if they never do anything. I even added a folder to the preferences and still nothing.

**Comment by kengruven** [comment]
Good points.

One half-answer: saving pipelines hasn't been implemented yet (#1), and that would be the logical use for these.  "New" and "Close" don't work on arbitrary files that are part of a pipeline, for example.  They operate on pipeline documents themselves.

Another half-answer: I *tend* to leave the default menuitems in place, because sometimes they have unintended uses.  (This used to be much more of an issue back when we had Desk Accessories ... I'm totally dating myself here.)  For example, you can't Cut or Paste an operation yet, but those menuitems can still be used when editing any text field.  I admit those particular menuitems don't seem to have any other use, but I guess I didn't think removing them was a priority.

I'm working on a couple ways to make it easier to use and re-use data sources.  I'm also thinking about how saving pipelines ought to work (which could give more purpose to the File menu).  No promises, but I hear you: the mostly-dimmed File menu right now is confusing.

**Comment by kengruven** [comment]
In 1.2.3, I removed the standard (but so far unused) document menuitems, and added "New Pipeline with file...", which lets you choose a file that way, if you wish.

There's now 3 ways to open a file, including the File menu, so I'm calling this one done.

(There's still work to be done with making the other methods easier to use, but there are other issues filed about that.)
