### ISSUE TITLE
Generate JSON gives empty objects

### ISSUE THREAD

**Issue by DandyDev** [kengruven/strukt-bugs#16]
I'm trying to parse a JSON file, select a part of it, and generate a new JSON file from it. The generated JSON seems to have only empty objects. It does have the right number of objects though.

Steps to reproduce:

- Download this dataset (it's small): https://www.govtrack.us/api/v2/role?current=true&role_type=senator
- Create the following Pipeline with that file:

![pipeline](http://dandydev.net/share/Screen-Shot-2017-07-07-22-11-23.png)

Am I doing something wrong? Because currently, this is the output:

![output](http://dandydev.net/share/Screen-Shot-2017-07-07-22-14-38.png)

**Comment by kengruven** [comment]
It looks like you're doing it right.  Unfortunately, Strukt tries to be nice, and in this case, two nice features combine to just be confusing:

 - The JSON generator pretty-prints the JSON (one line per key)
 - The table view only displays one line of text

As a result, in the table view, all you see is "{".  The rest of the data is there -- it's just on the 'next line' of each record, and there's no way to see the next line of a table cell.

**Quick fix:** use the text view (press command-3, or click the "abc" icon in the toolbar).

(BTW, you probably want linewise?=N, to create a single JSON document, rather than 100 little ones.)

I agree that the default in this case is rather unclear right now.  If you have any ideas on what I could do to improve it, I'm all ears.  I have some long-term ideas but it's entirely possible there's an easy improvement that I just haven't thought of yet.

Thanks for writing in about this!  If you ran into trouble here, I'm sure other people have, too.

**Comment by kengruven** [comment]
Also, I just noticed that "Generate JSON" is turning `null` into the string `"<null>"`, which is a bug.  Oops.  I'm fixing that now.

**Comment by DandyDev** [comment]
> (BTW, you probably want linewise?=N, to create a single JSON document, rather than 100 little ones.)

I actually want 1 JSON object per line :)

> As a result, in the table view, all you see is "{". The rest of the data is there -- it's just on the 'next line' of each record, and there's no way to see the next line of a table cell.

When I added a Write File operation at the end of the pipeline, I got a zero-byte file back.

**Comment by kengruven** [comment]
Hmm.  This works for me:

![senators](https://user-images.githubusercontent.com/22565/27987692-85251640-63c6-11e7-992b-8ea3077516c1.png)

Did you set the field on "Write to File", so it knows which field to write?  (One of the next major features is a proper logging system.  I'll add a log message for this case.)

FWIW, if you're using version 1.2.4, the output of the pipeline (in the view on the right) will be the values it actually wrote to disk.

**Comment by DandyDev** [comment]
Ah, I forgot to add the `field` parameter to the Write to File operation.
One remark though: I'd expect `linewise? Y` in the Generate JSON operation, to generate condensed JSON objects that occupy one line per object. When I use Write to File, that is not what I'm seeing. Each JSON object covers multiple lines.

I'd like to be able to write one JSON object per line when generating JSON from cards.

**Comment by kengruven** [comment]
I'm happy it's (mostly) working for you now!

Interesting point about generating condensed JSON.  I have considered adding a flag to GenerateJSON to generate "compact" versus "pretty" JSON.  That would be pretty easy to do.

I'm a *little* hesitant to put this behind `linewise?`, too, because that flag determines how to treat the input, and compact/pretty determines how to generate the output -- they're distinct features, in my mind.  But it might make sense to use the `linewise?` value as a default indicator for the output style.  I'll play around with it a bit.

Thanks for the idea!

**Comment by kengruven** [comment]
OK, so in the next version, there's a new flag "compact?", and if you set it to Y, then you get single-line-per-object JSON.

Also, if you set "linewise?=Y", then you get "compact?=Y" automatically.  That's a little weird to me (there's no other flags that have a default of "same value as some other flag, if that other flag was specified"), but I agree it's usually what the user will want, and it's not *that* complex.

Here's a sneak preview:

![senators linewise](https://user-images.githubusercontent.com/22565/28002318-ed48bd62-64e8-11e7-9a18-e621ede4020a.png)

**Comment by DandyDev** [comment]
That sounds exactly like what I need! :) Thanks for implementing this so quickly!

As far as I'm concerned this solves my issue, so it can be closed.

**Comment by kengruven** [comment]
Great!

I'm going to keep this issue open until I actually ship all of it, though -- with any luck, this week.

**Comment by kengruven** [comment]
I found an unrelated crashing bug, so I had to ship a new release today anyway.  Strukt 1.2.5 is out, and it includes all of the "Generate JSON" improvements mentioned above (but not the new logging system).

Be sure to tell all your friends about how great Strukt is, and how helpful the tech support is!  :-)  And let me know if you think of any other cases where Strukt *almost* fills a need.

**Comment by kengruven** [comment]
In version 1.3 (submitting to the Mac App Store right now), there's a log which appears and shows you warnings, like if you Write but tell it to use a field which has no data.

You can see a sneak preview of what it looks like over in bug #14.
