### ISSUE TITLE
Date parsing feature request to support time

### ISSUE THREAD

**Issue by garycmartin** [kengruven/strukt-bugs#18]
Currently date parsing (Parse String -> Date) generates whole day date results. I'm working with live sensor data logs, it would be lovely if the date parsing supported full DateTime (e.g. 2017-09-19T04:53:41Z).

**Comment by kengruven** [comment]
It actually does support *some* time formats -- unfortunately, just not that one.

Technical: Strukt first tries a fixed-format ISO-8601 parser, and if that doesn't work, it tries OS X's "data detector" to look for date/times.  The ISO-8601 format it's using requires milliseconds, so it would work if you were to change it to "2017-09-19T04:53:41.000Z".

Of course, what we all really want is full ISO-8601 support.  OS X 10.12 has built-in support, and I've been avoiding it because I don't want to abandon 10.11 yet.  But there's some third-party ones that look like they would work just fine.

I'll see what I can do here.

**Comment by kengruven** [comment]
In the meantime, here's another workaround, since JS supports ISO-8601 date parsing:

    Compute[fn="new Date(my_date_string)" into="date"]

("Ken, are you going to use that JavaScript operation as the get-out-of-jail-free card for every last feature that Strukt doesn't yet support?"  Yes.  Yes I am.  :-)

**Comment by kengruven** [comment]
Strukt 1.4 now has a full ISO-8601 parser, so dates like "2017-09-19T04:53:41Z" will be parsed including their time components.

**Comment by garycmartin** [comment]
Great, thanks. Working well!

**Comment by kengruven** [comment]
Great!
