### ISSUE TITLE
`Read from URL` seems to clip at 1,373 rows of data

### ISSUE THREAD

**Issue by garycmartin** [kengruven/strukt-bugs#21]
Using `Read from URL` seems to fill 1,373 rows of data before starting to pushing earlier data out of the buffer e.g. reading a known 1,770 rows of data from a URL results in 1,373 rows, where the first 397 rows are dropped\lost. If I take that same (json) data set and save it to local disk, then use `Read File` I successfully load in all 1,770 rows of data to play with.

**Comment by kengruven** [comment]
Hmm, that's really strange.  I've certainly loaded much bigger resources than that.  [Here's a URL]( https://raw.githubusercontent.com/datasets/s-and-p-500/master/data/data.csv) I've been playing with, for example, which is header + 1748 rows.  It works fine for me.

I've got some ideas for some things to investigate, but nothing is jumping out at me yet.

**Comment by kengruven** [comment]
I still have no idea why this would occur, and especially why it would drop records from the *start*.

Are you doing ReadFromURL->ParseJSON?  You could try adding a type="binary" flag to the "Read from URL" operation.  This removes the internal "Decode Bytes->Text" and "Split Text into Lines" operations from that, which you don't need for JSON parsing.  (This puts data in the field "bytes", so you'll need to add a field="bytes" flag to your ParseJSON operation.)  If that works, then it suggests there's a bug in one of those two operations.

(In Strukt 1.4, it optimizes ReadFile->ParseJSON this way automatically, but not ReadFromURL->ParseJSON, which could explain why there's a difference -- but not what the bug is.)

Another test you could try:

    Read from URL (url=...) (type="binary")
    Compute (fn="bytes.length")
    Sum Rows (field="result")

This should give the total number of bytes in the file.  If it's too small, that suggests that ReadFromURL is broken.  If it's the correct size, that suggests that one of the other operations (like Decode or Split) is at fault.

I don't suppose the URL is publicly accessible?

**Comment by garycmartin** [comment]
Using the ReadFromURL type="binary" -> ParseJSON field="bytes" displayed the same 1,373 rows, however while experimenting with this I noticed that it's feeling like a caching glitch of some kind, and I'm constantly hitting a cache of old data. This is odd as I've quit Strukt between data runs, and even rebooted a few times. The URL I'm requesting is querying live sensor data that grows over time (sorry it's not publicly accessible so can't share). The same query URL string from a few days ago may have had 1,373 rows, but today should return 1,807 rows. If I modify the URL string (e.g. changing the requested datetime by one second) I am getting the expected full 1,807 rows. Is there any state cached somewhere by Strukt I can clear/reset? I've also noticed that I can query that past URL in Strukt without the required authorisation custom header, and it shows the data, if I query the same URL string from, say curl in the Terminal, or another application, I get the expected 'invalid authorisation token' error. So there definitely seems to be some locally cached data somewhere here ;)

**Comment by kengruven** [comment]
Aah, that explains it!

The default operating system URLCache persists to disk, so it's not surprising that restarting doesn't help.  I'm not sure offhand where it's actually stored, but I'll see if I can find out.

Based on this information, the problem seems to be that I'm using a caching mode that's too aggressive.  I'm going to turn it down a notch for the next release.

**Comment by kengruven** [comment]
Strukt 1.4.1 is out, and it should be less aggressive with caching.  Let me know if it works any better for you.

**Comment by garycmartin** [comment]
Looking good, have been testing today and is working well, thanks!

**Comment by kengruven** [comment]
Great!
