### ISSUE TITLE
Temporarily disable a card

### ISSUE THREAD

**Issue by tiguchi** [kengruven/strukt-bugs#4]
It would be nice if some cards could be temporarily disabled without having to delete and recreate them. I know they tend to successively build on each other. But I have a final "write to file" output card which I'd like to switch off so I can edit the other cards above and make some changes that can be seen in the result pane.

**Comment by kengruven** [comment]
There is actually a way to do this!  I'll be the first to admit, though, that it's somewhat klugey, and not terribly visible.

The menu item Edit &rarr; Toggle Comment (shortcut: `#`) will change the operation under the cursor into a "NOP", and set the (unused) flag "op" to its previous title.  When you press `#` again, the NOP will change back to its original operation.

Clearly, this feature needs some design love.  Here's my initial ideas:
 - [ ] The Edit menu feels very far away.  Adding a context menu to operations, and putting it there, could help.  I'll try that.
 - [ ] Is this feature poorly named?  Looking at it today, I don't much care for "Toggle Comment".  Perhaps "Disable Operation" / "Enable Operation"?
 - [ ] Simply changing an operation to "NOP" makes all of its flags into warnings, which is ugly and perhaps confusing.  I'd like to draw disabled operations in a special style.  I have no specific plans here but I'll give it some thought.
 - [ ] I'll write some documentation for this feature.  (I know nobody reads the manual, anyway, but it's easy to do, and it can't hurt.)

**Comment by tiguchi** [comment]
Oh, that's great! From a coding POV that's actually quite intuitive. I guess now it clicked with me.

Intuitively I expected some context menu interaction with the cards and hoped for an option that says: "disable". It didn't cross my mind to look into the edit menu.

How about some contextual tool bar buttons that show up right in the editor window once a card is highlighted? These buttons could also provide the other options from the edit menu (insert before, after) and a delete option. Hovering over any button would reveal the name of the action and the associated keyboard shortcut so it's easier to learn.

On a related note I was struggling a bit with using just the keyboard. Knowing next to nothing about the application in the beginning made me use the mouse a lot for adding new cards and flags. Today I looked into the manual and saw that there are keyboard shortcuts.

I would have expected that hitting return (or tab) actually confirms an input (e.g. operation selection or the selection of a flag name) and moves the cursor automatically to the right, so it's possible to type in values right away. That felt quite frustrating in the beginning, but I guess that's a matter of learning new tricks.

However, maybe you could add some overlay instructions for first time users, that show the next possible (and logical) keystroke for completing an operation

**Comment by kengruven** [comment]
This is great feedback.  Some thoughts:

- It's great to hear how other people use Strukt.  I've done almost no user testing (mea culpa) so I'm hearing great ideas I never would have thought of.
- Toolbar buttons for common editing operations sound like a reasonable request.  Will do.  An overhaul of the toolbar is already in progress for some other upcoming features.
- I agree the keyboard learning situation isn't so great yet.  I have several ideas, and a visual overlay is one of them.  It just hasn't been a top priority yet.
- Great idea on making "return" confirm a flag and jump directly to editing the flag value.  (Really, what else would you want to do, then?)  I'm used to typing operations in a slightly different way, so that didn't occur to me, but it makes total sense.
- I'm on the fence about having "return" on an operation type jump to editing a flag, too, since not all operations have mandatory flags.  Looking over the sample pipelines, though, most do, so I'm willing to give it a try.

**Comment by kengruven** [comment]
1.1.2 is live on the Mac App Store, and includes these improvements:
 - This feature is now called "Disable Operation" (or "Enable Operation", if it's disabled)
 - There's a context menu, if you right-click on an operation, which includes this
 - Disabled operations (NOP) don't show warning badges for any fields

This issue is now (mostly) fixed, so I'm closing it.  I've added the other items to my internal bug tracker.
