### ISSUE TITLE
Strukt Summer Deal Invite!

### ISSUE THREAD

**Issue by Budlehunt** [kengruven/strukt-bugs#44]
Hi,

Bundlehunt is inviting Strukt to our upcoming 2020 Summer Deal that is planned to go live on the 3rd. Of August.
We are featuring some of the most prestigious Mac software that’ll fit any Mac user’s needs.

We’ve partnered with top-notch companies i.e; Corel Corporation, DigiDNA, Bjango, Skylum, Prosoft Eng, Phase Five Systems, Paragon Software and many more… 

Here are the deets:Every app is to be sold at a discounted price, customers can choose any number of software offered through this limited-time offer. So you’re free to place your app for a discounted price same as if you’re offering it in a single deal. Cause the price of each app is calculated separately in the customer’s order.We handle marketing of the bundle through our store, various media channels and top-popular affiliated partners.An exclusive email newsletters will be sent several times to all our customers through the bundle event. [we’ve around 900K Mac-only segment of customers].We’ve an amazing network of affiliate partners who promote the bundle to their own customer’s email list and their websites as well.The bundle is directly placed on our homepage, and payment is handled through our store as well.We discuss the best price point for your app in order to get the best results. Discount price is negotiable between developer's team and our team.Developer's revenue share is fairly 50% of every license sold of his appDevelopers get paid in 14 days after the deal is over. Payments are delivered to either your Paypal or as wire transfer.Upon agreeing on technical and financial details, a signed agreement will be required from both parties; Bundlehunt and the developer.
We do think that Strukt would be a great fit for this bundle, we're kicking things off on the 3rd. Of August. If you're interested, let me know so we can move forward with the financial and technical part.

Have a great day and stay safe!

Yasmina Nabil
Bundlehunt.com
Growth Marketing Manager
yasmina@bundlehunt.com

**Comment by kengruven** [comment]
Hi Yasmina.  Thanks for the offer.

Unfortunately, this sounds like too much work for me.  Since it wouldn't be handled through the Mac App Store (correct?), I'd need to find/build/integrate my own systems for licensing, installation (DropDMG?), upgrades (Sparkle?), and so on.  Then I'd need to maintain this alternative distribution system indefinitely, so that these users could get regular upgrades.

I simply don't have the resources to commit to that.  It's possible I could do some kind of small summer discount, if you wanted to advertise for me, but all sales/downloads would still have to be through the Mac App Store.

Thanks for thinking of me, though.  Maybe next year I'll have an app that's more amenable to this type of deal.
