### ISSUE TITLE
Trying to learn how to use Strukt, but having JSON issues

### ISSUE THREAD

**Issue by newtreen** [kengruven/strukt-bugs#45]
The attached files shows an example of a structure I want to parse and the desired output.  I need to be able to read the JSON file and create something like the output file.

The fields need some custom processing and parsing, and I can't figure out how to do that in Strukt.  I was hoping that the data structure parsing was easily configurable.  Otherwise I would be writing Python scripts for everything, please help, thanks!
[Problem Example Files.zip](https://github.com/kengruven/strukt-bugs/files/4957213/Problem.Example.Files.zip)

**Comment by kengruven** [comment]
I love a challenge!

I managed to get it most of the way there.  Admittedly, it's not the most intuitive pipeline, as Strukt is better at flat tables than nested structures.  I used a couple Javascript operations (is that cheating?).

![Screen Shot 2020-07-21 at 8 38 13 PM](https://user-images.githubusercontent.com/22565/88131588-2da9fc00-cb92-11ea-9f38-6eb3c0bf2b55.png)

First, I dragged input.json from the Finder into Strukt.  This gave me:
 - "Read File" filename=~/Downloads/Problem/input.json
 - "Parse JSON"

which looks like a good start.

Second, I saw that the "metadata" column has almost-but-not-quite-JSON (semicolons instead of commas), so I used:
 - "Compute" fn=`metadata.replace(/;/g, ",")` into=`metadata`

to convert it into real JSON, and a:
 - "Parse JSON" field=`metadata` linewise?=`Y`

to parse those into new columns.

Then, the big problem is that not every input row has a "metadata" value, so the ones without it got removed from the output.  To work around that, I added:
 - "Compute" var=`$` fn=`$.metadata || "{}"` into=`metadata`

before the semicolon replacement operation.  That's an obscure (but documented!) feature of the Compute operation which was intended for dealing with keys which aren't valid JS variable names -- but in this case it works for dealing with missing values, too.

Now there's just a couple minor formatting issues.  Let me know if you're still stuck on those and I'll take another look.  Slap a "Generate TSV" on the end, and it's good to go.

It's always neat to see new ways people are trying to use Strukt.  I can see here a couple little features which would have made this much simpler.  There should be a dedicated "replace in string" operation (so you don't have to know the Javascript syntax for it), and "Parse JSON"-linewise shouldn't drop rows with missing values.  I'll add those to my list for the next version.

**Comment by newtreen** [comment]
That's great, are there other languages I can use besides JS?  Thank you very much!

**Comment by kengruven** [comment]
In Strukt?  No, just JS.  It's built into macOS, and it uses the same data types as JSON, so it's mostly work I had to do anyway.

It's unlikely I'll put the effort into embedding other general-purpose languages (especially big complex ones like Python) in Strukt.  The embedding and integration looks like it'd be a lot of work -- and if you want to write Python programs, there are certainly easier ways than putting one line at a time into little boxes!  I've got bigger fish to fry.

**Comment by kengruven** [comment]
Strukt 1.7.5 is now available, and it includes two small improvements which are relevant to this workflow:

 1. There's a new "Replace Text" operation which makes text modification easier
 2. The "Parse JSON" operation will skip rows with blank or invalid values, rather than removing them

I've included a screenshot of the pipeline you can now create.  It gives the same results as the earlier one, but is a bit more straightforward.

Please feel free to re-open this bug if there's anything I missed.

![Screen Shot 2020-08-01 at 12 54 25 PM](https://user-images.githubusercontent.com/22565/89129878-b7709800-d4b5-11ea-96d5-4c6386d49e53.png)

**Comment by newtreen** [comment]
Thanks!
