### ISSUE TITLE
v1.7.6 x-axis with data/time stamps line chart issue

### ISSUE THREAD

**Issue by garycmartin** [kengruven/strukt-bugs#48]
Hi, just a quick report that v1.7.6 seems to have introduced an issue when using date/times as the x-axis on line charts. It looks like it's not correctly scaling the x data across the available x-axis min/max. Results look like a narrow, squished, chart starting in the middle of the window, where each record is plotted with one pixel increments (instead adjusting to span the available chart space). Line charts with many records end up plotting across the right half of the window with the left half blank (e.g. plot starts from middle of screen and increment one pixel at a time to the right).

**Comment by kengruven** [comment]
Oh, that's not good.  I'm sorry.

Worse, I can't seem to reproduce the problem here.  Here's the "Consumer Price Index" demo that's included with Strukt, on my Mac:

![Screen Shot 2020-08-10 at 9 07 29 AM](https://user-images.githubusercontent.com/22565/89804400-fbcceb00-dae8-11ea-827b-4ccd293d12d1.png)

I did make some minor changes to how the range is computed, but the data should always be centered in the view.  Do you have some sample data you can share which demonstrates the problem?  I'll keep looking but I don't see any obvious issues yet.

**Comment by garycmartin** [comment]
Here's an example cvs file, and two screen shots. Note that using an integer for the x-axis (an incrementing PacketNum in this case) distributes fine, but switching to the Received date/time stamps shows the issue. Thanks for your support!

**Comment by kengruven** [comment]
Ah, I see the problem!  I tested big ranges, small ranges, and date ranges -- but I didn't test small(ish) date ranges.  Oops.  I'll fix that.

BTW, can I ask what Mac and version of macOS you're using?  It looks like there's a funny shadow beneath the operation blocks that shouldn't be there.

**Comment by garycmartin** [comment]
It's a MacBook Pro (15-inch, 2016) 2.7 GHz Quad-Core Intel Core i7 (Radeon Pro 460 4 GB Intel HD Graphics 530 1536 MB) running Catalina (10.15.6). Yes the odd solid shadow appeared not that long ago (maybe a month?) but not sure if it appeared after a struct update (possibly after copy/paste of operations was added).

**Comment by kengruven** [comment]
Hmm.  I was half expecting it to be some ancient barely-supported hardware or OS.  There's no reason that should be weird on a recent MacBook Pro.

I did make some minor changes to pipeline drawing in June, but nothing that should have had any impact on the shadow.  Well, I need to change it again in the near future for some other features I want to support, so I'll try to keep it as simple as possible, and hopefully it'll resolve this.

**Comment by kengruven** [comment]
There is now a Strukt 1.7.7, which should fix this problem.  I really hope it doesn't break anything else!  Let me know how it works for you.

**Comment by garycmartin** [comment]
Thanks, the graph range is now working well! :) New break unfortunately. If you have more than one document open, switching to the line chart view is usually fine for one, but will crash if you try to view the line chart for a second document, e.g. I can open multiple documents, but I've not been able to view more than one of them as a line chart without triggering a crash.

<img width="1080" alt="Screenshot 2020-08-14 at 18 31 14" src="https://user-images.githubusercontent.com/5605304/90276800-691bab80-de5c-11ea-85d1-5164dc59a886.png">

**Comment by kengruven** [comment]
Yay! ... Darn.

Thanks for the stack trace.  From what I can tell, it's not multiple windows, but the y-values of the data.  It's actually the part that's drawing the y-axis that's failing.  I'll have to do some more investigation.

So far, it looks like:
 - I changed the range-picker so it's able to accept tiny ranges as valid, without assuming they're basically 0 and adding extra padding
 - but the y-axis-drawing-function (e.g., so when you draw points ranging from -7.2 to 13.6, it puts ticks at -5.0, 0.0, 5.0, etc., rather than just dividing (13.6--7.2)/10 and putting ticks at odd values -5.12, -3.04, -0.96, etc.) can't handle a nearly-zero range, so it crashes

For example, if you make a chart with y=1000000 at every point (y range = 0.0), that crashes.

"And that one sank into the swamp. So I built a third. That burned down, fell over, and then sank into the swamp. But the fourth one stayed up!"

**Comment by kengruven** [comment]
OK, I have a fix that I think is much more robust.  If you have any sample data which crashes Strukt 1.7.7, I'd be happy to test it before I release.  Otherwise, I'm planning to submit this fix to the Mac App Store later today.

**Comment by kengruven** [comment]
Hello again!  I kind of dropped off the radar for a little bit.  Can you confirm that the x-scaling is working correctly for you with the latest version (1.7.9)?

**Comment by garycmartin** [comment]
Yes all has been looking good and stable here with the current release, many thanks!

**Comment by kengruven** [comment]
Great!  Thanks for the confirmation.
